# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='mapel',
            new_name='mata_pelajaran',
        ),
    ]
