# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0003_auto_20180214_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
